SELECT  [IDAccionCorrectora]
      ,[IDReunionGrupo]
      ,[NumFase]
      ,[Nombre]
      ,[IDUsuarioResponsable]
      ,format([FechaPrevistaFin], 'dd/MM/yyyy HH:mm:ss' ) as FechaPrevistaFin
      ,[CorreoElectronico]
      ,[Aprobada]
      ,[Anulada]
      ,[IDPrioridad]
      ,[RequisitoLegal]
      ,[ImpactoPotencial]
      ,[ProbabilidadPotencial]
      ,[Gravedad]
  FROM [Prevencion].[dbo].[ITP_RG_ACCIONES_CORRECTORAS]
