SELECT  [IDReunionGrupo]
      ,[IDFlujo]
      ,[IDCentro]
      ,[IDEmpresa]
      ,[IDDepartamento]
      ,[IDUnidadOrg]
      ,[FechaCreacion]
      ,format([FechaUltimaModificacion], 'dd/MM/yyyy HH:mm:ss' ) as FechaUltimaModificacion
      ,[IDUsuarioUltimaModificacion]
      ,format([Fecha], 'dd/MM/yyyy HH:mm:ss' ) as Fecha
      ,[Hora]
      ,[IDGrupoIniciador]
      ,[Estado]
      ,[IDGrupoResponsableFaseActual]
      ,[FaseActual]
      ,[IDGrupoResponsableFase1]
      ,[IDUsuarioEnvioFase1]
      ,format([FechaEnvioFase1], 'dd/MM/yyyy HH:mm:ss' ) as FechaEnvioFase1
      ,[IDNivel]
      ,[IDLetra]
      ,[Lugar]
      ,[Duracion]
      ,[BreveDescripcion]
      ,[Tema]
      ,[Asistentes]
      ,[NumAsistentes]
      ,[PuntosTratados]
      ,[SugerenciasAportadas]
      ,[TemasPendientes]
      ,[IDResponsable]
      ,[IDGrupoResponsableFase2]
      ,[IDUsuarioEnvioFase2]
      ,format([FechaEnvioFase2], 'dd/MM/yyyy HH:mm:ss' ) as FechaEnvioFase2
      ,[Observaciones]
      ,[Aprobacion]
      ,[IDGrupoResponsableFase3]
      ,[IDUsuarioEnvioFase3]
      ,format([FechaEnvioFase3], 'dd/MM/yyyy HH:mm:ss' ) as FechaEnvioFase3
      ,[IDValoracion1]
      ,[IDValoracion2]
      ,[IDValoracion3]
      ,[IDValoracion4]
      ,[IDValoracion5]
      ,format([FechaFinalizacion], 'dd/MM/yyyy HH:mm:ss' ) as FechaFinalizacion
      ,[esNuevoTipo]
  FROM [Prevencion].[dbo].[ITP_REUNION_GRUPO]
