SELECT        ITP_PSM_RESPUESTAS.IDInformeInv, ITP_PSM_RESPUESTAS.IDRespuestaPSM, ITP_PSM_PREGUNTAS.IDPreguntaPSM, ITP_PSM_RESPUESTAS.IDElementoPSM, ITP_PSM_ELEMENTOS.NombreElemento, 
                         ITP_PSM_RESPUESTAS.Texto AS TextoPreg, ITP_PSM_RESPUESTAS.Respuesta, ITP_PSM_PREGUNTAS.Baja
FROM            ITP_PSM_RESPUESTAS FULL OUTER JOIN
                         ITP_PSM_PREGUNTAS ON ITP_PSM_RESPUESTAS.IDPreguntaPSM = ITP_PSM_PREGUNTAS.IDPreguntaPSM  JOIN
                         ITP_PSM_ELEMENTOS ON ITP_PSM_RESPUESTAS.IDElementoPSM = ITP_PSM_ELEMENTOS.IDElementoPSM order by IDInformeInv