SELECT        ITP_PSM_RESPUESTAS_INFINV2.IDInformeInv, ITP_PSM_RESPUESTAS_INFINV2.IDRespuestaPSM, ITP_PSM_RESPUESTAS_INFINV2.IDPreguntaPSM, ITP_PSM_RESPUESTAS_INFINV2.IDElementoPSM, 
                         ITP_PSM_ELEMENTOS.NombreElemento, ITP_PSM_PREGUNTAS_INFINV2.Texto AS TextoPreg, ITP_PSM_RESPUESTAS_INFINV2.Respuesta, ITP_PSM_PREGUNTAS_INFINV2.Baja
FROM            ITP_PSM_RESPUESTAS_INFINV2 left JOIN
                         ITP_PSM_PREGUNTAS_INFINV2 ON ITP_PSM_RESPUESTAS_INFINV2.IDPreguntaPSM = ITP_PSM_PREGUNTAS_INFINV2.IDPreguntaPSM INNER JOIN
                         ITP_PSM_ELEMENTOS ON ITP_PSM_RESPUESTAS_INFINV2.IDElementoPSM = ITP_PSM_ELEMENTOS.IDElementoPSM order by IDInformeInv