SELECT        
IDOps,
format(FechaRealizacion, 'dd/MM/yyyy HH:mm:ss' ) as FechaRealizacion,
IDCentro,
IDEmpresa,
IDUsuarioObservador,
IDUsuarioObservador2,
IDGrupoIniciador,
IDFlujo,
IDUnidadOrg,
format(FechaTopeRealizacion, 'dd/MM/yyyy HH:mm:ss' ) as FechaTopeRealizacion,
TareaAObservar,
IDUsuarioResponsable,
Programada, 
Planificada,
IdGrupoResponsableFaseActual,
FaseActual,
format(FechaUltimaModificacion, 'dd/MM/yyyy HH:mm:ss' ) as FechaUltimaModificacion,
IDUsuarioUltimaModificacion,
Estado,
IDGravedad,
format(FechaCreacion, 'dd/MM/yyyy HH:mm:ss' ) as FechaCreacion,
IDGrupoResponsableFase1,
IDResponsableGrupoFase1, 
IDUsuarioEnvioFase1,
format(FechaEnvioFase1, 'dd/MM/yyyy HH:mm:ss' ) as FechaEnvioFase1,
IDContratista,
AnomaliasYRiegosObs,
Formacion,
Procedimiento,
Normas,
Instrucciones,
Entrenamiento,
Epi,
Equipos,
Herramientas,
Recomendaciones,
NombrePersonaObservada, 
NumeroPermisoTrabajo,
IDGrupoResponsableFase2,
IDResponsableGrupoFase2,
IDUsuarioEnvioFase2,
format(FechaEnvioFase2, 'dd/MM/yyyy HH:mm:ss' ) as FechaEnvioFase2,
Observacion,
HorasEmpleadas,
NearMisses,
IDSeguridad
FROM            ITP_OPS order by IDOps asc