SELECT        ITP_ANALISIS_EVENTO.IDEvento, ITP_ANALISIS_EVENTO.IDCentro, ITP_ANALISIS_EVENTO.IDEmpresa, 
format( ITP_ANALISIS_EVENTO.FechaEvento,  'dd/MM/yyyy HH:mm:ss') as FechaSuceso, 
format( ITP_ANALISIS_EVENTO.FechaCreacion,  'dd/MM/yyyy HH:mm:ss') as FechaCreacion, 
format( ITP_ANALISIS_EVENTO.FechaUltimaModificacion,  'dd/MM/yyyy HH:mm:ss') as FechaUltimaModificacion,
ITP_ANALISIS_EVENTO.IDUsuarioUltMod,
ITP_ANALISIS_EVENTO.SinInfInvestigacion,
ITP_ANALISIS_EVENTO.IDUnidadOrg,
ITP_INFORME_MEDICO.IDAnalisis AS IDAnalisis_Med,
ITP_INFORME_MEDICO.IDInformeMed,
ITP_INFORME_MEDICO.IDFlujo, 
ITP_INFORME_MEDICO.IDUsuarioUltimaModificacion,
ITP_INFORME_MEDICO.Estado,
ITP_INFORME_MEDICO.FaseActual,
ITP_INFORME_MEDICO.IDGrupoResponsableFase1, 
ITP_INFORME_MEDICO.IDResponsableGrupoFase1,
ITP_INFORME_MEDICO.IDUsuarioEnvioFase1, 
format( ITP_INFORME_MEDICO.FechaEnvioFase1,  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase1,
ITP_INFORME_MEDICO.IDContratista,
ITP_INFORME_MEDICO.NumExpediente, 
ITP_INFORME_MEDICO.InItinere,
ITP_INFORME_MEDICO.ImplicacionVehiculosCirculando,
ITP_INFORME_MEDICO.Recaida,
ITP_INFORME_MEDICO.NombreApellidosTrabajador,
ITP_INFORME_MEDICO.Turno, 
ITP_INFORME_MEDICO.DiaSemana,
ITP_INFORME_MEDICO.Experiencia,
ITP_INFORME_MEDICO.HoraLaboral,
ITP_INFORME_MEDICO.Consecuencia,
ITP_INFORME_MEDICO.TrabajoHabitual, 
ITP_INFORME_MEDICO.CambioDestino,
ITP_INFORME_MEDICO.AtendidoPor,
ITP_INFORME_MEDICO.ObservacionesFase1,
ITP_INFORME_MEDICO.IDGrupoResponsableFase2, 
ITP_INFORME_MEDICO.IDResponsableGrupoFase2,
ITP_INFORME_MEDICO.IDUsuarioEnvioFase2, 
format( ITP_INFORME_MEDICO.FechaEnvioFase2,  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase2,
ITP_INFORME_MEDICO.NIF, ITP_INFORME_MEDICO.Edad, 
format( ITP_INFORME_MEDICO.FechaIngresoEmpresa,  'dd/MM/yyyy HH:mm:ss') as FechaIngresoEmpresa, 
format( ITP_INFORME_MEDICO.FechaUltimoCambio,  'dd/MM/yyyy HH:mm:ss') as FechaUltimoCambio,
ITP_INFORME_MEDICO.RecibidoAsistenciaEn,
ITP_INFORME_MEDICO.TratadoPor, 
format( ITP_INFORME_MEDICO.FechaBaja,  'dd/MM/yyyy HH:mm:ss') as FechaBaja, 
format( ITP_INFORME_MEDICO.FechaAlta,  'dd/MM/yyyy HH:mm:ss') as FechaAlta,
ITP_INFORME_MEDICO.IDGrupoResponsableFase3,
ITP_INFORME_MEDICO.IDResponsableGrupoFase3,
ITP_INFORME_MEDICO.IDUsuarioEnvioFase3, 
format( ITP_INFORME_MEDICO.FechaEnvioFase3,  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase3,
ITP_INFORME_MEDICO.IDNaturalezaTrabajo,
ITP_INFORME_MEDICO.OtroNaturalezaTrabajo,
ITP_INFORME_MEDICO.IDAgenteLesion,
ITP_INFORME_MEDICO.OtroAgenteLesion,
ITP_INFORME_MEDICO.IDTipoAccidente,
ITP_INFORME_MEDICO.OtroTipoAccidente,
ITP_INFORME_MEDICO.IDCausaAccidente,
ITP_INFORME_MEDICO.OtroCausaAccidente,
ITP_INFORME_MEDICO.AccidentesAnteriores, 
ITP_INFORME_MEDICO.AccidenteSimilares,
ITP_INFORME_MEDICO.Observaciones,
ITP_INFORME_MEDICO.IdGrupoResponsableFaseActual,
ITP_INFORME_MEDICO.ClasificacionAccidenteSinBaja, 
ITP_INFORME_MEDICO.AccidenteNoRelacionadoConTarea,
ITP_INFORME_INV2_GRAVEDAD_REAL.IDEvento,
ITP_INFORME_INV2_GRAVEDAD_REAL.IDInfFase4,
ITP_INFORME_INV2_GRAVEDAD_REAL.IDGravedadRealLesion,
ITP_INFORME_INV2_GRAVEDAD_REAL.Personas,
ITP_INFORME_INV2_GRAVEDAD_REAL.Externa

FROM            ITP_ANALISIS_EVENTO inner JOIN
                         ITP_INFORME_MEDICO ON ITP_ANALISIS_EVENTO.IDEvento = ITP_INFORME_MEDICO.IDEvento
                         left join ITP_INFORME_INV2_GRAVEDAD_REAL ON ITP_ANALISIS_EVENTO.IDEvento = ITP_INFORME_INV2_GRAVEDAD_REAL.IDEvento  
                         order by ITP_INFORME_MEDICO.IDEvento asc