SELECT        ITP_ANALISIS.[IDAnalisis] as IDAnalisisA
      ,ITP_ANALISIS.[IDCentro]
      ,ITP_ANALISIS.[IDEmpresa]
      ,ITP_ANALISIS.[Suceso] as SucesoA
      ,format( ITP_ANALISIS.[FechaSuceso],  'dd/MM/yyyy HH:mm:ss') as FechaSuceso
      ,format( ITP_ANALISIS.[FechaCreacion], 'dd/MM/yyyy HH:mm:ss') as FechaCreacion
      ,format(ITP_ANALISIS.[FechaUltimaModificacion], 'dd/MM/yyyy HH:mm:ss') as FechaUltimaModificacion
      ,ITP_ANALISIS.[IDUsuarioUltimaModificacin]
      ,ITP_ANALISIS.[SinInfInvestigacion]
      ,ITP_ANALISIS.[IDUnidadOrg], 
      ITP_INFORME_INVEST_PR227.[IDInformeInv]
      ,ITP_INFORME_INVEST_PR227.[IDAnalisis] as IDAnalisisB
      ,ITP_INFORME_INVEST_PR227.[IDFlujo]
      ,format( ITP_INFORME_INVEST_PR227.[FechaCreacion],  'dd/MM/yyyy HH:mm:ss') as FechaCreacion
      ,format( ITP_INFORME_INVEST_PR227.[FechaUltimaModificacion],  'dd/MM/yyyy HH:mm:ss') as FechaUltimaModificacion
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioModificacion]
      ,ITP_INFORME_INVEST_PR227.[IDEstado]
      ,ITP_INFORME_INVEST_PR227.[IdGrupoResponsableFaseActual]
      ,ITP_INFORME_INVEST_PR227.[FaseActual]
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase1]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase1]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase1]
      ,ITP_INFORME_INVEST_PR227.[FechaEnvioFase1]
      ,ITP_INFORME_INVEST_PR227.[IDTipoAccidente]
      ,ITP_INFORME_INVEST_PR227.[ImplicacionVehiculoCirculando]
      ,ITP_INFORME_INVEST_PR227.[FugaGas]
      ,ITP_INFORME_INVEST_PR227.[DerrameLiquido]
      ,ITP_INFORME_INVEST_PR227.[Incendio]
      ,ITP_INFORME_INVEST_PR227.[ExplosionConfinada]
      ,ITP_INFORME_INVEST_PR227.[ExplosionNoConfinada]
      ,ITP_INFORME_INVEST_PR227.[Bleve]
      ,ITP_INFORME_INVEST_PR227.[SinClasificar]
      ,ITP_INFORME_INVEST_PR227.[FugaMenor]
      ,ITP_INFORME_INVEST_PR227.[DerrameMenor]
      ,ITP_INFORME_INVEST_PR227.[ConatoFuego]
      ,ITP_INFORME_INVEST_PR227.[Averia]
      ,ITP_INFORME_INVEST_PR227.[Perturbacion]
      ,ITP_INFORME_INVEST_PR227.[Suceso]
      ,ITP_INFORME_INVEST_PR227.[IDConsecuenciaSeguridad]
      ,ITP_INFORME_INVEST_PR227.[IDConsecuenciaMedioAmbiente]
      ,ITP_INFORME_INVEST_PR227.[IDConsecuenciaFinanciera]
      ,ITP_INFORME_INVEST_PR227.[Consecuencia]
      ,ITP_INFORME_INVEST_PR227.[MedioAmbiente]
      ,ITP_INFORME_INVEST_PR227.[ContaminacionMarina]
      ,ITP_INFORME_INVEST_PR227.[Calidad]
      ,ITP_INFORME_INVEST_PR227.[IDDuracion]
      ,ITP_INFORME_INVEST_PR227.[IDDepartamento]
      ,ITP_INFORME_INVEST_PR227.[IDUnidadOrg]
      ,ITP_INFORME_INVEST_PR227.[IDContratista]
      ,ITP_INFORME_INVEST_PR227.[TrabajoQRealizaba]
      ,ITP_INFORME_INVEST_PR227.[EPI]
      ,ITP_INFORME_INVEST_PR227.[EPIUtilizado]
      ,ITP_INFORME_INVEST_PR227.[Lugar]
      ,ITP_INFORME_INVEST_PR227.[DannosPropiedad]
      ,ITP_INFORME_INVEST_PR227.[EvaluacionPerdidas]
      ,ITP_INFORME_INVEST_PR227.[Descripcion]
      ,ITP_INFORME_INVEST_PR227.[CausasInmediatas]
      ,ITP_INFORME_INVEST_PR227.[AccAdoptadasRespuesta]
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase2]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase2]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase2]
      ,format( ITP_INFORME_INVEST_PR227.[FechaEnvioFase2],  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase2
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaDisenno]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaHardware]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaGestionMantenimiento]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaCondicionError]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaOrdenLimpieza]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaProcedimientoOperacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaFormacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaComunicacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaMetaIncompatible]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaOrganizacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaMedioProteccion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaSupervisionOrganizacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaFactorPersonal]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaFactorMaterial]
      ,ITP_INFORME_INVEST_PR227.[IDCausaBasicaCondicionTrabajo]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataDisenno]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataHardware]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataGestionMantenimiento]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataCondicionError]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataOrdenLimpieza]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataProcedimientoOperacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataFormacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataComunicacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataMetaIncompatible]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataOrganizacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataMedioProteccion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataSupervisionOrganizacion]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataFactorPersonal]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataFactorMaterial]
      ,ITP_INFORME_INVEST_PR227.[IDCausaInmediataCondicionTrabajo]
      ,ITP_INFORME_INVEST_PR227.[JustificarCausa]
      ,ITP_INFORME_INVEST_PR227.[ComentadoConResponsable]
      ,ITP_INFORME_INVEST_PR227.[PasoComiteFase2]
      ,ITP_INFORME_INVEST_PR227.[ObservacionesPasoComite2]
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase3]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase3]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase3]
      ,format( ITP_INFORME_INVEST_PR227.[FechaEnvioFase3],  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase3
      ,ITP_INFORME_INVEST_PR227.[PasoComiteFase3]
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase4]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase4]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase4]
      ,format( ITP_INFORME_INVEST_PR227.[FechaEnvioFase4],  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase4
      ,ITP_INFORME_INVEST_PR227.[ArbolCausa]
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase5]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase5]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase5]
      ,format( ITP_INFORME_INVEST_PR227.[FechaEnvioFase5],  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase5
      ,ITP_INFORME_INVEST_PR227.[ValoracionInforme]
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase6]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase6]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase6]
      ,format( ITP_INFORME_INVEST_PR227.[FechaEnvioFase6],  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase6
      ,ITP_INFORME_INVEST_PR227.[Aprobacion]
      ,format( ITP_INFORME_INVEST_PR227.[FechaFinalizacion],  'dd/MM/yyyy HH:mm:ss') as FechaFinalizacion
      ,ITP_INFORME_INVEST_PR227.[IDGrupoResponsableFase7]
      ,ITP_INFORME_INVEST_PR227.[IDResponsableGrupoFase7]
      ,ITP_INFORME_INVEST_PR227.[IDUsuarioEnvioFase7]
      ,format( ITP_INFORME_INVEST_PR227.[FechaEnvioFase7],  'dd/MM/yyyy HH:mm:ss') as FechaEnvioFase7
      ,ITP_INFORME_INVEST_PR227.[Eficaz]
      ,ITP_INFORME_INVEST_PR227.[Motivo]
      ,ITP_INFORME_INVEST_PR227.[SolucionReal]
      ,ITP_INFORME_INVEST_PR227.[Costes]
      ,ITP_INFORME_INVEST_PR227.[RevisarEvaluacionRiesgos]
      ,ITP_INFORME_INVEST_PR227.[IncidenteIndustrialEsPSE]
      ,ITP_INFORME_INVEST_PR227.[IDNivelAccidenteIndustrial]
      ,ITP_INFORME_INVEST_PR227.[Observaciones]
      ,ITP_INFORME_INVEST_PR227.[CantidadFugadaDerramada]
      ,ITP_INFORME_INVEST_PR227.[Energetica]
      ,ITP_INFORME_INVEST_PR227.[ProductoFugadoDerramado]
      ,ITP_INFORME_INVEST_PR227.[Seguridad]
      ,ITP_INFORME_INVEST_PR227.[Liderazgo]
      ,ITP_INFORME_INVEST_PR227.[ReglasYNormas]
      ,ITP_INFORME_INVEST_PR227.[Competencias]
      ,ITP_INFORME_INVEST_PR227.[Implantacion]
      ,ITP_INFORME_INVEST_PR227.[PartesImplicadas]
      ,ITP_INFORME_INVEST_PR227.[EvaluacioRiesgos]
      ,ITP_INFORME_INVEST_PR227.[Registros]
      ,ITP_INFORME_INVEST_PR227.[ManualesYPro]
      ,ITP_INFORME_INVEST_PR227.[VarOPYRelevos]
      ,ITP_INFORME_INVEST_PR227.[Interfaces]
      ,ITP_INFORME_INVEST_PR227.[EstandaresPTS]
      ,ITP_INFORME_INVEST_PR227.[GestionCambios]
      ,ITP_INFORME_INVEST_PR227.[PTAMarcha]
      ,ITP_INFORME_INVEST_PR227.[PrepEmerg]
      ,ITP_INFORME_INVEST_PR227.[InspYMto]
      ,ITP_INFORME_INVEST_PR227.[ElemCriticos]
      ,ITP_INFORME_INVEST_PR227.[PermTrabajo]
      ,ITP_INFORME_INVEST_PR227.[Contratista]
      ,ITP_INFORME_INVEST_PR227.[Investigacion]
      ,ITP_INFORME_INVEST_PR227.[Auditorias]
      ,ITP_INFORME_INVEST_PR227.[NearMisses]
FROM            ITP_ANALISIS full JOIN
                         ITP_INFORME_INVEST_PR227 ON ITP_ANALISIS.IDAnalisis = ITP_INFORME_INVEST_PR227.IDAnalisis ;

