SELECT        ITP_SIM_ACCIONES_CORRECTORAS.*, ITP_ACCIONES_CORRECTORAS.MedioAmbiente
FROM            ITP_SIM_ACCIONES_CORRECTORAS left JOIN
                         ITP_ACCIONES_CORRECTORAS ON ITP_SIM_ACCIONES_CORRECTORAS.IDAccionCorrectora = ITP_ACCIONES_CORRECTORAS.IDAccionCorrectora