SELECT [IDAccionCorrectora]
      ,[IDSimulacro]
      ,[NumFase]
      ,[Nombre]
      ,[IDUsuarioResponsable]
      ,[FechaPrevistaFin]
      ,[CorreoElectronico]
      ,[Aprobada]
      ,[Anulada]
      ,[IDPrioridad]
      ,[RequisitoLegal]
      ,[ImpactoPotencial]
      ,[ProbabilidadPotencial]
      ,[Gravedad]
  FROM [Prevencion].[dbo].[ITP_SIM_ACCIONES_CORRECTORAS]
