SELECT  [IDUsuario]
      ,[IDUsuarioRed]
      ,[Nombre]
      ,[IDCentro]
      ,[IDDepartamento]
      ,[IDUnidadOrg]
      ,[CorreoElectronico]
      ,[CursoObservaciones]
      ,[ResponsableIndices]
      ,[Baja]
      ,[Idioma]
      ,[FormacionArbolCausas]
  FROM [Prevencion].[dbo].[ITP_USUARIOS]
