SELECT        ITP_ACCIONES_CORRECTORAS.IDAccionCorrectora, ITP_ACCIONES_CORRECTORAS.IDOrigenAC, ITP_ORIGEN_AC.NombreOrigen, ITP_ORIGEN_AC.OrigenPrevencion, ITP_ACCIONES_CORRECTORAS.IDCentro, 
                         ITP_ACCIONES_CORRECTORAS.IDEmpresa, ITP_ACCIONES_CORRECTORAS.CodOrigen, ITP_ACCIONES_CORRECTORAS.Nombre, ITP_ACCIONES_CORRECTORAS.IDUsuarioResponsable, 
                         ITP_ACCIONES_CORRECTORAS.OtroResponsable, ITP_ACCIONES_CORRECTORAS.FechaPrevistaFin, ITP_ACCIONES_CORRECTORAS.FechaRealFin, ITP_ACCIONES_CORRECTORAS.OrdenTrabajo, 
                         ITP_ACCIONES_CORRECTORAS.Coste, ITP_ACCIONES_CORRECTORAS.Descripcion, ITP_ACCIONES_CORRECTORAS.NumeroProyecto, ITP_ACCIONES_CORRECTORAS.FechaCreacion, 
                         ITP_ACCIONES_CORRECTORAS.FechaUltimaModificacion, ITP_ACCIONES_CORRECTORAS.IDUsuarioUltimaModificacion, ITP_ACCIONES_CORRECTORAS.Anulada, ITP_ACCIONES_CORRECTORAS.IDUnidadOrg, 
                         ITP_ACCIONES_CORRECTORAS.MedioAmbiente, ITP_ACCIONES_CORRECTORAS.Calidad, ITP_ACCIONES_CORRECTORAS.FechaPrevistaFinAct, ITP_ACCIONES_CORRECTORAS.IDPrioridad, 
                         ITP_ACCIONES_CORRECTORAS.Difundir, ITP_ACCIONES_CORRECTORAS.RequisitoLegal, ITP_ACCIONES_CORRECTORAS.NearMisses, ITP_ACCIONES_CORRECTORAS.ImpactoPotencial, 
                         ITP_ACCIONES_CORRECTORAS.ProbabilidadPotencial, ITP_ACCIONES_CORRECTORAS.Gravedad, ITP_ACCIONES_CORRECTORAS.DescripcionEvidencias
FROM            ITP_ACCIONES_CORRECTORAS FULL JOIN
                         ITP_ORIGEN_AC ON ITP_ACCIONES_CORRECTORAS.IDOrigenAC = ITP_ORIGEN_AC.IDOrigenAC 
