SELECT  
    CT_SOLICITUDES_CAMBIO.IDSolicitudCambio,
    CT_SOLICITUDES_CAMBIO.IDFlujo,
    CT_SOLICITUDES_CAMBIO.IDCentro,
    CT_SOLICITUDES_CAMBIO.FechaHora,
    CT_SOLICITUDES_CAMBIO.Estado,
    CT_SOLICITUDES_CAMBIO.IDGrupoResponsableFaseActual,
    CT_SOLICITUDES_CAMBIO.FaseActual,
    CT_SOLICITUDES_CAMBIO.FechaCreacion,
    CT_SOLICITUDES_CAMBIO.FechaAprobacion,
    CT_SOLICITUDES_CAMBIO.FechaTerminacion,
    CT_SOLICITUDES_CAMBIO.FechaFinalizacion,
    CT_SOLICITUDES_CAMBIO.FechaUltimaModificacion,
    CT_SOLICITUDES_CAMBIO.IDUsuarioUltimaModificacion,
    CT_SOLICITUDES_CAMBIO.esMenor,
    CT_SOLICITUDES_CAMBIO.Prioridad,
    CT_SOLICITUDES_CAMBIO.Observaciones,
    CT_SOLICITUDES_CAMBIO.esNuevoTipo,

    CT_SOLICITUDES_CAMBIO_FASE1.IDGrupoResponsableFase1,
    CT_SOLICITUDES_CAMBIO_FASE1.IDUsuarioEnvioFase1,
    CT_SOLICITUDES_CAMBIO_FASE1.FechaEnvioFase1,
    CT_SOLICITUDES_CAMBIO_FASE1.BreveDesc,
    CT_SOLICITUDES_CAMBIO_FASE1.IDFabrica,
    CT_SOLICITUDES_CAMBIO_FASE1.IDPlanta,
    CT_SOLICITUDES_CAMBIO_FASE1.IDUnidad,

    CT_SOLICITUDES_CAMBIO_FASE1.IDTipoSC,
    mTipoSC.Valor AS TipoSC,

    CT_SOLICITUDES_CAMBIO_FASE1.Duracion,

    CT_SOLICITUDES_CAMBIO_FASE1.IDMotivo,
    mMotivo.Valor AS Motivo,

    CT_SOLICITUDES_CAMBIO_FASE1.Cambio_Propuesto,
    CT_SOLICITUDES_CAMBIO_FASE1.Causas_Cambio,

    CT_SOLICITUDES_CAMBIO_FASE1.IDImplicaCambio,
    mImplica.Valor AS ImplicaCambio,

    CT_SOLICITUDES_CAMBIO_FASE1.Fecha_Terminacion_Solicitada,

    CT_SOLICITUDES_CAMBIO_FASE2.IDGrupoResponsableFase2,
    CT_SOLICITUDES_CAMBIO_FASE2.IDUsuarioEnvioFase2,
    CT_SOLICITUDES_CAMBIO_FASE2.FechaEnvioFase2,
    CT_SOLICITUDES_CAMBIO_FASE2.Observaciones AS [Observaciones-f2],

    CT_SOLICITUDES_CAMBIO_FASE2.IDRecomienda,
    mRec2.Valor AS Recomienda_f2,

    CT_SOLICITUDES_CAMBIO_FASE2.IDPrioridad,

    CT_SOLICITUDES_CAMBIO_FASE3.IDGrupoResponsableFase3,
    CT_SOLICITUDES_CAMBIO_FASE3.IDUsuarioEnvioFase3,
    CT_SOLICITUDES_CAMBIO_FASE3.FechaEnvioFase3,
    CT_SOLICITUDES_CAMBIO_FASE3.Observaciones AS [Observaciones-f3],

    CT_SOLICITUDES_CAMBIO_FASE3.IDRecomienda AS ID_recomienda_f3,
    mRec3.Valor AS Recomienda_f3,

    CT_SOLICITUDES_CAMBIO_FASE4.IDGrupoResponsableFase4,
    CT_SOLICITUDES_CAMBIO_FASE4.IDUsuarioEnvioFase4,
    CT_SOLICITUDES_CAMBIO_FASE4.FechaEnvioFase4,
    CT_SOLICITUDES_CAMBIO_FASE4.Observaciones AS [Observaciones-f4],

    CT_SOLICITUDES_CAMBIO_FASE4.IDRecomienda AS ID_recomienda_f4,
    mRec4.Valor AS Recomienda_f4,

    CT_SOLICITUDES_CAMBIO_FASE4.PresupuestoPrevio,

    CT_SOLICITUDES_CAMBIO_FASE5.IDGrupoResponsableFase5,
    CT_SOLICITUDES_CAMBIO_FASE5.IDUsuarioEnvioFase5,
    CT_SOLICITUDES_CAMBIO_FASE5.FechaEnvioFase5,
    CT_SOLICITUDES_CAMBIO_FASE5.Observaciones AS [Observaciones-f5],

    CT_SOLICITUDES_CAMBIO_FASE5.IDRecomienda AS ID_recomienda_f5,
    mRec5.Valor AS Recomienda_f5,

    CT_SOLICITUDES_CAMBIO_FASE6.IDGrupoResponsableFase6,
    CT_SOLICITUDES_CAMBIO_FASE6.IDUsuarioEnvioFase6,
    CT_SOLICITUDES_CAMBIO_FASE6.FechaEnvioFase6,
    CT_SOLICITUDES_CAMBIO_FASE6.Observaciones AS [Observaciones-f6],
    CT_SOLICITUDES_CAMBIO_FASE6.RequiereHAZOP,
    CT_SOLICITUDES_CAMBIO_FASE6.ImplicacionesMA,
    CT_SOLICITUDES_CAMBIO_FASE6.AfectaAAtmosfera,
    CT_SOLICITUDES_CAMBIO_FASE6.AfectaAAguas,
    CT_SOLICITUDES_CAMBIO_FASE6.AfectaAResiduos,
    CT_SOLICITUDES_CAMBIO_FASE6.AfectaASuelo,
    CT_SOLICITUDES_CAMBIO_FASE6.NivelRiesgo,
    CT_SOLICITUDES_CAMBIO_FASE6.TipoCambio,
    CT_SOLICITUDES_CAMBIO_FASE6.RequiereGuiaSMAR,
    CT_SOLICITUDES_CAMBIO_FASE6.AdjuntadaGuiaSMAR,

    CT_SOLICITUDES_CAMBIO_FASE7.IDGrupoResponsableFase7,
    CT_SOLICITUDES_CAMBIO_FASE7.IDUsuarioEnvioFase7,
    CT_SOLICITUDES_CAMBIO_FASE7.FechaEnvioFase7,
    CT_SOLICITUDES_CAMBIO_FASE7.Observaciones AS [Observaciones-f7],
    CT_SOLICITUDES_CAMBIO_FASE7.EstudioSeguridad,
    CT_SOLICITUDES_CAMBIO_FASE7.EstudioPrevAmbiental,
    CT_SOLICITUDES_CAMBIO_FASE7.RevisionEvRiesgos,
    CT_SOLICITUDES_CAMBIO_FASE7.ImplicacionesMA AS ImplicacionesMA_f7,
    CT_SOLICITUDES_CAMBIO_FASE7.LicenciaObras,
    CT_SOLICITUDES_CAMBIO_FASE7.ProyectoOficial,
    CT_SOLICITUDES_CAMBIO_FASE7.ComunicacionAIndustria,
    CT_SOLICITUDES_CAMBIO_FASE7.AfectaAAtmosfera AS AfectaAAtmosfera_f7,
    CT_SOLICITUDES_CAMBIO_FASE7.AfectaAAguas AS AfectaAAguas_f7,
    CT_SOLICITUDES_CAMBIO_FASE7.AfectaAResiduos AS AfectaAResiduos_f7,
    CT_SOLICITUDES_CAMBIO_FASE7.LibroContraexplosiones,
    CT_SOLICITUDES_CAMBIO_FASE7.AdjuntadaGuiaSMAR AS AdjuntadaGuiaSMAR_f7,
    CT_SOLICITUDES_CAMBIO_FASE7.RequiereHAZOP AS RequiereHAZOP_f7,

    CT_SOLICITUDES_CAMBIO_FASE8.IDUsuarioEnvioFase8,
    CT_SOLICITUDES_CAMBIO_FASE8.FechaEnvioFase8,
    CT_SOLICITUDES_CAMBIO_FASE8.Observaciones AS [Observaciones-f8],

    CT_SOLICITUDES_CAMBIO_FASE8.IDRecomienda AS ID_recomienda_f8,
    mRec8.Valor AS Recomienda_f8,

    CT_SOLICITUDES_CAMBIO_FASE8_1.IDGrupoResponsableFase8_1,
    CT_SOLICITUDES_CAMBIO_FASE8_1.IDUsuarioEnvioFase8_1,
    CT_SOLICITUDES_CAMBIO_FASE8_1.FechaEnvioFase8_1,
    CT_SOLICITUDES_CAMBIO_FASE8_1.Observaciones AS [Observaciones-f8_1],

    CT_SOLICITUDES_CAMBIO_FASE9.IDGrupoResponsableFase9,
    CT_SOLICITUDES_CAMBIO_FASE9.IDUsuarioEnvioFase9,
    CT_SOLICITUDES_CAMBIO_FASE9.FechaEnvioFase9,
    CT_SOLICITUDES_CAMBIO_FASE9.Observaciones AS [Observaciones-f9],
    CT_SOLICITUDES_CAMBIO_FASE9.PresupuestoAprobado,
    CT_SOLICITUDES_CAMBIO_FASE9.FechaEstimadaFin,
    CT_SOLICITUDES_CAMBIO_FASE9.AccionesHAZOPimplemen,
    CT_SOLICITUDES_CAMBIO_FASE9.N_AFI_OT,
    CT_SOLICITUDES_CAMBIO_FASE9.AdjuntadoHAZOP,

    CT_SOLICITUDES_CAMBIO_FASE10.IDGrupoResponsableFase10,
    CT_SOLICITUDES_CAMBIO_FASE10.IDUsuarioEnvioFase10,
    CT_SOLICITUDES_CAMBIO_FASE10.FechaEnvioFase10,
    CT_SOLICITUDES_CAMBIO_FASE10.Observaciones AS [Observaciones-f10],
    CT_SOLICITUDES_CAMBIO_FASE10.GradoAvance,

    CT_SOLICITUDES_CAMBIO_FASE11.IDGrupoResponsableFase11,
    CT_SOLICITUDES_CAMBIO_FASE11.IDUsuarioEnvioFase11,
    CT_SOLICITUDES_CAMBIO_FASE11.FechaEnvioFase11,
    CT_SOLICITUDES_CAMBIO_FASE11.Observaciones AS [Observaciones-f11],
    CT_SOLICITUDES_CAMBIO_FASE11.Proteccion_Individual,
    CT_SOLICITUDES_CAMBIO_FASE11.Lista_Faltas,
    CT_SOLICITUDES_CAMBIO_FASE11.Manual_Operacion,
    CT_SOLICITUDES_CAMBIO_FASE11.Plan_Emergencia,
    CT_SOLICITUDES_CAMBIO_FASE11.Personal_Operacion,
    CT_SOLICITUDES_CAMBIO_FASE11.Programas_Mantenimiento,
    CT_SOLICITUDES_CAMBIO_FASE11.AceptadoOperaciones,

    CT_SOLICITUDES_CAMBIO_FASE12.IDGrupoResponsableFase12,
    CT_SOLICITUDES_CAMBIO_FASE12.IDUsuarioEnvioFase12,
    CT_SOLICITUDES_CAMBIO_FASE12.FechaEnvioFase12,
    CT_SOLICITUDES_CAMBIO_FASE12.Observaciones AS [Observaciones-f12],
    CT_SOLICITUDES_CAMBIO_FASE12.DocumentacionActualizada,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoHAZOP,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoEstudioSeguridad,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoEstudioPrevAmbiental,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoRevisionEvRiesgos,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoImplicacionesMA,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoLicenciaObras,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoProyectoOficial,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoComunicacionAIndustria,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadoLibroContraexplosiones,
    CT_SOLICITUDES_CAMBIO_FASE12.FinalizadaGuiaSMAR

FROM CT_SOLICITUDES_CAMBIO
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE1 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE1.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE2 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE2.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE3 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE3.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE4 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE4.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE5 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE5.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE6 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE6.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE7 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE7.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE8 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE8.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE8_1 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE8_1.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE9 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE9.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE10 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE10.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE11 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE11.IDSolicitudCambio
LEFT JOIN CT_SOLICITUDES_CAMBIO_FASE12 ON CT_SOLICITUDES_CAMBIO.IDSolicitudCambio = CT_SOLICITUDES_CAMBIO_FASE12.IDSolicitudCambio

LEFT JOIN CT_MAESTROS mTipoSC ON CT_SOLICITUDES_CAMBIO_FASE1.IDTipoSC = mTipoSC.IDMaestro
LEFT JOIN CT_MAESTROS mMotivo ON CT_SOLICITUDES_CAMBIO_FASE1.IDMotivo = mMotivo.IDMaestro
LEFT JOIN CT_MAESTROS mImplica ON CT_SOLICITUDES_CAMBIO_FASE1.IDImplicaCambio = mImplica.IDMaestro
LEFT JOIN CT_MAESTROS mRec2 ON CT_SOLICITUDES_CAMBIO_FASE2.IDRecomienda = mRec2.IDMaestro
LEFT JOIN CT_MAESTROS mRec3 ON CT_SOLICITUDES_CAMBIO_FASE3.IDRecomienda = mRec3.IDMaestro
LEFT JOIN CT_MAESTROS mRec4 ON CT_SOLICITUDES_CAMBIO_FASE4.IDRecomienda = mRec4.IDMaestro
LEFT JOIN CT_MAESTROS mRec5 ON CT_SOLICITUDES_CAMBIO_FASE5.IDRecomienda = mRec5.IDMaestro
LEFT JOIN CT_MAESTROS mRec8 ON CT_SOLICITUDES_CAMBIO_FASE8.IDRecomienda = mRec8.IDMaestro